/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as InscripcionRouteImport } from './routes/inscripcion'
import { Route as PlantelRouteImport } from './routes/plantel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionRoute = InscripcionRouteImport.update({
  id: '/inscripcion',
  path: '/inscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantelRoute = PlantelRouteImport.update({
  id: '/plantel',
  path: '/plantel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/inscripcion': typeof InscripcionRoute
  '/plantel': typeof PlantelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/inscripcion': typeof InscripcionRoute
  '/plantel': typeof PlantelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/inscripcion': typeof InscripcionRoute
  '/plantel': typeof PlantelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipos' | '/inscripcion' | '/plantel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipos' | '/inscripcion' | '/plantel'
  id: '__root__' | '/' | '/equipos' | '/inscripcion' | '/plantel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquiposRoute: typeof EquiposRoute
  InscripcionRoute: typeof InscripcionRoute
  PlantelRoute: typeof PlantelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripcion': {
      id: '/inscripcion'
      path: '/inscripcion'
      fullPath: '/inscripcion'
      preLoaderRoute: typeof InscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantel': {
      id: '/plantel'
      path: '/plantel'
      fullPath: '/plantel'
      preLoaderRoute: typeof PlantelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquiposRoute: EquiposRoute,
  InscripcionRoute: InscripcionRoute,
  PlantelRoute: PlantelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
