/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmadoRouteImport } from './routes/armado'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as PlantelRouteImport } from './routes/plantel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmadoRoute = ArmadoRouteImport.update({
  id: '/armado',
  path: '/armado',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantelRoute = PlantelRouteImport.update({
  id: '/plantel',
  path: '/plantel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armado': typeof ArmadoRoute
  '/equipos': typeof EquiposRoute
  '/plantel': typeof PlantelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armado': typeof ArmadoRoute
  '/equipos': typeof EquiposRoute
  '/plantel': typeof PlantelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armado': typeof ArmadoRoute
  '/equipos': typeof EquiposRoute
  '/plantel': typeof PlantelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/armado' | '/equipos' | '/plantel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/armado' | '/equipos' | '/plantel'
  id: '__root__' | '/' | '/armado' | '/equipos' | '/plantel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmadoRoute: typeof ArmadoRoute
  EquiposRoute: typeof EquiposRoute
  PlantelRoute: typeof PlantelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armado': {
      id: '/armado'
      path: '/armado'
      fullPath: '/armado'
      preLoaderRoute: typeof ArmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantel': {
      id: '/plantel'
      path: '/plantel'
      fullPath: '/plantel'
      preLoaderRoute: typeof PlantelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmadoRoute: ArmadoRoute,
  EquiposRoute: EquiposRoute,
  PlantelRoute: PlantelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
